lane :bonjour do

  scan(
    code_coverage: true
  )
  xcov

end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "ozonePowered/fastlane-demo-moc2-1",
      name: version, # Nom de la version sur GitHub
      tag_name: "v#{version}", # last_git_tag(),
      description: changelog_from_git_commits,
      commitish: "master"
    )
  end
end
